select CURRENT_TIMESTAMP as checktime, 'TaskCustomerAccess' as entitytype, t1.object_id as id, 'T_TASKCUSTOMERACCESS' as table1, 'TASK_ID' as column1, t1.TASK_ID as value1, '' as table2, '' as column2, '' as value2, 'PARENT' as checktype, 'PNUL' as errorcode, 'the column with the parent reference is not filled' as errordetails from T_TASKCUSTOMERACCESS t1 where t1.TASK_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysCheckSelect' as entitytype, t1.object_id as id, 'T_SEC_CHECKSELECT' as table1, 'OPERATION_ID' as column1, t1.OPERATION_ID as value1, '' as table2, '' as column2, '' as value2, 'PARENT' as checktype, 'PNUL' as errorcode, 'the column with the parent reference is not filled' as errordetails from T_SEC_CHECKSELECT t1 where t1.OPERATION_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysOperation' as entitytype, t1.object_id as id, 'T_SEC_OPERATION' as table1, 'ROOTSECURITY_ID' as column1, t1.ROOTSECURITY_ID as value1, '' as table2, '' as column2, '' as value2, 'PARENT' as checktype, 'PNUL' as errorcode, 'the column with the parent reference is not filled' as errordetails from T_SEC_OPERATION t1 where t1.ROOTSECURITY_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysAdminSettings' as entitytype, t1.object_id as id, 'T_SEC_ADMINSETTINGS' as table1, 'ROOTSECURITY_ID' as column1, t1.ROOTSECURITY_ID as value1, '' as table2, '' as column2, '' as value2, 'PARENT' as checktype, 'PNUL' as errorcode, 'the column with the parent reference is not filled' as errordetails from T_SEC_ADMINSETTINGS t1 where t1.ROOTSECURITY_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysParamAddition' as entitytype, t1.object_id as id, 'T_SEC_PARAMADDITION' as table1, 'OPERATION_ID' as column1, t1.OPERATION_ID as value1, '' as table2, '' as column2, '' as value2, 'PARENT' as checktype, 'PNUL' as errorcode, 'the column with the parent reference is not filled' as errordetails from T_SEC_PARAMADDITION t1 where t1.OPERATION_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'CustomerApiCall' as entitytype, t1.object_id as id, 'T_CUSTOMERAPICALL' as table1, 'PARENTOBJECT_ID' as column1, t1.PARENTOBJECT_ID as value1, '' as table2, '' as column2, '' as value2, 'PARENT' as checktype, 'PNUL' as errorcode, 'the column with the parent reference is not filled' as errordetails from T_CUSTOMERAPICALL t1 where t1.PARENTOBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskApiCall' as entitytype, t1.object_id as id, 'T_TASKAPICALL' as table1, 'PARENTOBJECT_ID' as column1, t1.PARENTOBJECT_ID as value1, '' as table2, '' as column2, '' as value2, 'PARENT' as checktype, 'PNUL' as errorcode, 'the column with the parent reference is not filled' as errordetails from T_TASKAPICALL t1 where t1.PARENTOBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskCustomerAccess' as entitytype, t1.object_id as id, 'T_TASKCUSTOMERACCESS' as table1, 'TASK_ID' as column1, t1.TASK_ID as value1, 'T_TASK' as table2, 'object_id' as column2, '' as value2, 'PARENT' as checktype, 'PMIS' as errorcode, 'a row is missing in the parent table of aggregate T_TASK' as errordetails from T_TASKCUSTOMERACCESS t1 left join T_TASK t2 on t1.TASK_ID = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysCheckSelect' as entitytype, t1.object_id as id, 'T_SEC_CHECKSELECT' as table1, 'OPERATION_ID' as column1, t1.OPERATION_ID as value1, 'T_SEC_OPERATION' as table2, 'object_id' as column2, '' as value2, 'PARENT' as checktype, 'PMIS' as errorcode, 'a row is missing in the parent table of aggregate T_SEC_OPERATION' as errordetails from T_SEC_CHECKSELECT t1 left join T_SEC_OPERATION t2 on t1.OPERATION_ID = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysOperation' as entitytype, t1.object_id as id, 'T_SEC_OPERATION' as table1, 'ROOTSECURITY_ID' as column1, t1.ROOTSECURITY_ID as value1, 'T_SEC_ROOTSECURITY' as table2, 'object_id' as column2, '' as value2, 'PARENT' as checktype, 'PMIS' as errorcode, 'a row is missing in the parent table of aggregate T_SEC_ROOTSECURITY' as errordetails from T_SEC_OPERATION t1 left join T_SEC_ROOTSECURITY t2 on t1.ROOTSECURITY_ID = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysAdminSettings' as entitytype, t1.object_id as id, 'T_SEC_ADMINSETTINGS' as table1, 'ROOTSECURITY_ID' as column1, t1.ROOTSECURITY_ID as value1, 'T_SEC_ROOTSECURITY' as table2, 'object_id' as column2, '' as value2, 'PARENT' as checktype, 'PMIS' as errorcode, 'a row is missing in the parent table of aggregate T_SEC_ROOTSECURITY' as errordetails from T_SEC_ADMINSETTINGS t1 left join T_SEC_ROOTSECURITY t2 on t1.ROOTSECURITY_ID = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysParamAddition' as entitytype, t1.object_id as id, 'T_SEC_PARAMADDITION' as table1, 'OPERATION_ID' as column1, t1.OPERATION_ID as value1, 'T_SEC_OPERATION' as table2, 'object_id' as column2, '' as value2, 'PARENT' as checktype, 'PMIS' as errorcode, 'a row is missing in the parent table of aggregate T_SEC_OPERATION' as errordetails from T_SEC_PARAMADDITION t1 left join T_SEC_OPERATION t2 on t1.OPERATION_ID = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'CustomerApiCall' as entitytype, t1.object_id as id, 'T_CUSTOMERAPICALL' as table1, 'PARENTOBJECT_ID' as column1, t1.PARENTOBJECT_ID as value1, 'T_CUSTOMER' as table2, 'object_id' as column2, '' as value2, 'PARENT' as checktype, 'PMIS' as errorcode, 'a row is missing in the parent table of aggregate T_CUSTOMER' as errordetails from T_CUSTOMERAPICALL t1 left join T_CUSTOMER t2 on t1.PARENTOBJECT_ID = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskApiCall' as entitytype, t1.object_id as id, 'T_TASKAPICALL' as table1, 'PARENTOBJECT_ID' as column1, t1.PARENTOBJECT_ID as value1, 'T_TASK' as table2, 'object_id' as column2, '' as value2, 'PARENT' as checktype, 'PMIS' as errorcode, 'a row is missing in the parent table of aggregate T_TASK' as errordetails from T_TASKAPICALL t1 left join T_TASK t2 on t1.PARENTOBJECT_ID = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskCustomerAccess' as entitytype, t1.object_id as id, 'T_TASKCUSTOMERACCESS' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, '' as table2, '' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'ANUL' as errorcode, 'the column containing the reference to the aggregate root is not filled' as errordetails from T_TASKCUSTOMERACCESS t1 where t1.aggregateroot_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysCheckSelect' as entitytype, t1.object_id as id, 'T_SEC_CHECKSELECT' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, '' as table2, '' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'ANUL' as errorcode, 'the column containing the reference to the aggregate root is not filled' as errordetails from T_SEC_CHECKSELECT t1 where t1.aggregateroot_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysOperation' as entitytype, t1.object_id as id, 'T_SEC_OPERATION' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, '' as table2, '' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'ANUL' as errorcode, 'the column containing the reference to the aggregate root is not filled' as errordetails from T_SEC_OPERATION t1 where t1.aggregateroot_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysAdminSettings' as entitytype, t1.object_id as id, 'T_SEC_ADMINSETTINGS' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, '' as table2, '' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'ANUL' as errorcode, 'the column containing the reference to the aggregate root is not filled' as errordetails from T_SEC_ADMINSETTINGS t1 where t1.aggregateroot_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysParamAddition' as entitytype, t1.object_id as id, 'T_SEC_PARAMADDITION' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, '' as table2, '' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'ANUL' as errorcode, 'the column containing the reference to the aggregate root is not filled' as errordetails from T_SEC_PARAMADDITION t1 where t1.aggregateroot_id is null union all
select CURRENT_TIMESTAMP as checktime, 'CustomerApiCall' as entitytype, t1.object_id as id, 'T_CUSTOMERAPICALL' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, '' as table2, '' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'ANUL' as errorcode, 'the column containing the reference to the aggregate root is not filled' as errordetails from T_CUSTOMERAPICALL t1 where t1.aggregateroot_id is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskApiCall' as entitytype, t1.object_id as id, 'T_TASKAPICALL' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, '' as table2, '' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'ANUL' as errorcode, 'the column containing the reference to the aggregate root is not filled' as errordetails from T_TASKAPICALL t1 where t1.aggregateroot_id is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskCustomerAccess' as entitytype, t1.object_id as id, 'T_TASKCUSTOMERACCESS' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, 'T_TASK' as table2, 'object_id' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'AMIS' as errorcode, 'the string is missing in the aggregate root table T_TASK' as errordetails from T_TASKCUSTOMERACCESS t1 left join T_TASK t2 on t1.aggregateroot_id = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysCheckSelect' as entitytype, t1.object_id as id, 'T_SEC_CHECKSELECT' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, 'T_SEC_ROOTSECURITY' as table2, 'object_id' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'AMIS' as errorcode, 'the string is missing in the aggregate root table T_SEC_ROOTSECURITY' as errordetails from T_SEC_CHECKSELECT t1 left join T_SEC_ROOTSECURITY t2 on t1.aggregateroot_id = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysOperation' as entitytype, t1.object_id as id, 'T_SEC_OPERATION' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, 'T_SEC_ROOTSECURITY' as table2, 'object_id' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'AMIS' as errorcode, 'the string is missing in the aggregate root table T_SEC_ROOTSECURITY' as errordetails from T_SEC_OPERATION t1 left join T_SEC_ROOTSECURITY t2 on t1.aggregateroot_id = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysAdminSettings' as entitytype, t1.object_id as id, 'T_SEC_ADMINSETTINGS' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, 'T_SEC_ROOTSECURITY' as table2, 'object_id' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'AMIS' as errorcode, 'the string is missing in the aggregate root table T_SEC_ROOTSECURITY' as errordetails from T_SEC_ADMINSETTINGS t1 left join T_SEC_ROOTSECURITY t2 on t1.aggregateroot_id = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'SysParamAddition' as entitytype, t1.object_id as id, 'T_SEC_PARAMADDITION' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, 'T_SEC_ROOTSECURITY' as table2, 'object_id' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'AMIS' as errorcode, 'the string is missing in the aggregate root table T_SEC_ROOTSECURITY' as errordetails from T_SEC_PARAMADDITION t1 left join T_SEC_ROOTSECURITY t2 on t1.aggregateroot_id = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'CustomerApiCall' as entitytype, t1.object_id as id, 'T_CUSTOMERAPICALL' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, 'T_CUSTOMER' as table2, 'object_id' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'AMIS' as errorcode, 'the string is missing in the aggregate root table T_CUSTOMER' as errordetails from T_CUSTOMERAPICALL t1 left join T_CUSTOMER t2 on t1.aggregateroot_id = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskApiCall' as entitytype, t1.object_id as id, 'T_TASKAPICALL' as table1, 'AGGREGATEROOT_ID' as column1, t1.AGGREGATEROOT_ID as value1, 'T_TASK' as table2, 'object_id' as column2, '' as value2, 'AGGREGATE_ROOT' as checktype, 'AMIS' as errorcode, 'the string is missing in the aggregate root table T_TASK' as errordetails from T_TASKAPICALL t1 left join T_TASK t2 on t1.aggregateroot_id = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'Task' as entitytype, t1.TASK_ID as id, 'LC_TASK_TAGS' as table1, 'TASK_ID' as column1, t1.TASK_ID as value1, 'T_TASK' as table2, 'object_id' as column2, '' as value2, 'COLLECTION_OWNER' as checktype, 'OMIS' as errorcode, 'the string is missing in the collection owner table T_TASK' as errordetails from LC_TASK_TAGS t1 left join T_TASK t2 on t1.TASK_ID = t2.object_id where t2.object_id is null union all
select CURRENT_TIMESTAMP as checktime, 'Customer' as entitytype, t1.object_id as id, 'T_CUSTOMER' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_CUSTOMER t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'Customer' as entitytype, t1.object_id as id, 'T_CUSTOMER' as table1, 'TYPE' as column1, cast(t1.TYPE as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_CUSTOMER t1 where t1.TYPE is null union all
select CURRENT_TIMESTAMP as checktime, 'Task' as entitytype, t1.object_id as id, 'T_TASK' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_TASK t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'Task' as entitytype, t1.object_id as id, 'T_TASK' as table1, 'TYPE' as column1, cast(t1.TYPE as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_TASK t1 where t1.TYPE is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskCustomerAccess' as entitytype, t1.object_id as id, 'T_TASKCUSTOMERACCESS' as table1, 'TASK_ID' as column1, cast(t1.TASK_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_TASKCUSTOMERACCESS t1 where t1.TASK_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskCustomerAccess' as entitytype, t1.object_id as id, 'T_TASKCUSTOMERACCESS' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_TASKCUSTOMERACCESS t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskCustomerAccess' as entitytype, t1.object_id as id, 'T_TASKCUSTOMERACCESS' as table1, 'TYPE' as column1, cast(t1.TYPE as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_TASKCUSTOMERACCESS t1 where t1.TYPE is null union all
select CURRENT_TIMESTAMP as checktime, 'RootDictionary' as entitytype, t1.object_id as id, 'T_ROOTDICTIONARY' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_ROOTDICTIONARY t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'RootDictionary' as entitytype, t1.object_id as id, 'T_ROOTDICTIONARY' as table1, 'TYPE' as column1, cast(t1.TYPE as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_ROOTDICTIONARY t1 where t1.TYPE is null union all
select CURRENT_TIMESTAMP as checktime, 'SysRootSecurity' as entitytype, t1.object_id as id, 'T_SEC_ROOTSECURITY' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_ROOTSECURITY t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysRootSecurity' as entitytype, t1.object_id as id, 'T_SEC_ROOTSECURITY' as table1, 'TYPE' as column1, cast(t1.TYPE as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_ROOTSECURITY t1 where t1.TYPE is null union all
select CURRENT_TIMESTAMP as checktime, 'SysCheckSelect' as entitytype, t1.object_id as id, 'T_SEC_CHECKSELECT' as table1, 'OPERATION_ID' as column1, cast(t1.OPERATION_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_CHECKSELECT t1 where t1.OPERATION_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysCheckSelect' as entitytype, t1.object_id as id, 'T_SEC_CHECKSELECT' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_CHECKSELECT t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysOperation' as entitytype, t1.object_id as id, 'T_SEC_OPERATION' as table1, 'ROOTSECURITY_ID' as column1, cast(t1.ROOTSECURITY_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_OPERATION t1 where t1.ROOTSECURITY_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysOperation' as entitytype, t1.object_id as id, 'T_SEC_OPERATION' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_OPERATION t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysAdminSettings' as entitytype, t1.object_id as id, 'T_SEC_ADMINSETTINGS' as table1, 'ROOTSECURITY_ID' as column1, cast(t1.ROOTSECURITY_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_ADMINSETTINGS t1 where t1.ROOTSECURITY_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysAdminSettings' as entitytype, t1.object_id as id, 'T_SEC_ADMINSETTINGS' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_ADMINSETTINGS t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysParamAddition' as entitytype, t1.object_id as id, 'T_SEC_PARAMADDITION' as table1, 'OPERATION_ID' as column1, cast(t1.OPERATION_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_PARAMADDITION t1 where t1.OPERATION_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'SysParamAddition' as entitytype, t1.object_id as id, 'T_SEC_PARAMADDITION' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_SEC_PARAMADDITION t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'CustomerApiCall' as entitytype, t1.object_id as id, 'T_CUSTOMERAPICALL' as table1, 'PARENTOBJECT_ID' as column1, cast(t1.PARENTOBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_CUSTOMERAPICALL t1 where t1.PARENTOBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'CustomerApiCall' as entitytype, t1.object_id as id, 'T_CUSTOMERAPICALL' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_CUSTOMERAPICALL t1 where t1.OBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskApiCall' as entitytype, t1.object_id as id, 'T_TASKAPICALL' as table1, 'PARENTOBJECT_ID' as column1, cast(t1.PARENTOBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_TASKAPICALL t1 where t1.PARENTOBJECT_ID is null union all
select CURRENT_TIMESTAMP as checktime, 'TaskApiCall' as entitytype, t1.object_id as id, 'T_TASKAPICALL' as table1, 'OBJECT_ID' as column1, cast(t1.OBJECT_ID as varchar(254)) as value1, '' as table2, '' as column2, '' as value2, 'MANDATORY' as checktype, 'MNUL' as errorcode, 'обязательное значение не заполнено' as errordetails from T_TASKAPICALL t1 where t1.OBJECT_ID is null